/**********************************************************************

	--- Qt Architect generated file ---

	File: FilterRuleEditorData.h
	Last generated: Mon Dec 15 22:40:17 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef FilterRuleEditorData_included
#define FilterRuleEditorData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qlistbox.h>
#include <qlined.h>

class FilterRuleEditorData : public QDialog
{
    Q_OBJECT

public:

    FilterRuleEditorData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~FilterRuleEditorData();

public slots:


protected slots:

    virtual void raiseRule();
    virtual void deleteRule();
    virtual void OkPressed();
    virtual void closePressed();
    virtual void lowerRule();
    virtual void newHighlight(int);
    virtual void newRule();

protected:
    QLineEdit* LineTitle;
    QLineEdit* LineSearch;
    QLineEdit* LineFrom;
    QLineEdit* LineTo;
    QListBox* RuleList;
    QPushButton* ApplyButton;
    QPushButton* deleteButton;

};

#endif // FilterRuleEditorData_included
