/**********************************************************************

	--- Qt Architect generated file ---

	File: open_topData.cpp
	Last generated: Tue Nov 25 22:51:09 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "open_topData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

open_topData::open_topData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 45056 )
{
	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 10, 10, 100, 30 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		dlgedit_Label_1->setFont( font );
	}
	dlgedit_Label_1->setText( "Channel/Nick:" );
	dlgedit_Label_1->setAlignment( 33 );
	dlgedit_Label_1->setMargin( -1 );

	nameSLE = new QLineEdit( this, "LineEdit_1" );
	nameSLE->setGeometry( 110, 10, 280, 30 );
	nameSLE->setMinimumSize( 10, 10 );
	nameSLE->setMaximumSize( 32767, 32767 );
	connect( nameSLE, SIGNAL(returnPressed()), SLOT(create_toplevel()) );
	nameSLE->setText( "" );
	nameSLE->setMaxLength( 32767 );
	nameSLE->setEchoMode( QLineEdit::Normal );
	nameSLE->setFrame( TRUE );

	QPushButton* dlgedit_PushButton_1;
	dlgedit_PushButton_1 = new QPushButton( this, "PushButton_1" );
	dlgedit_PushButton_1->setGeometry( 200, 50, 190, 30 );
	dlgedit_PushButton_1->setMinimumSize( 10, 10 );
	dlgedit_PushButton_1->setMaximumSize( 32767, 32767 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		dlgedit_PushButton_1->setFont( font );
	}
	connect( dlgedit_PushButton_1, SIGNAL(clicked()), SLOT(create_toplevel()) );
	dlgedit_PushButton_1->setText( "Ok" );
	dlgedit_PushButton_1->setAutoRepeat( FALSE );
	dlgedit_PushButton_1->setAutoResize( FALSE );
	dlgedit_PushButton_1->setAutoDefault( TRUE );

	QPushButton* dlgedit_PushButton_2;
	dlgedit_PushButton_2 = new QPushButton( this, "PushButton_2" );
	dlgedit_PushButton_2->setGeometry( 10, 50, 180, 30 );
	dlgedit_PushButton_2->setMinimumSize( 10, 10 );
	dlgedit_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_2, SIGNAL(clicked()), SLOT(terminate()) );
	dlgedit_PushButton_2->setText( "Cancel" );
	dlgedit_PushButton_2->setAutoRepeat( FALSE );
	dlgedit_PushButton_2->setAutoResize( FALSE );

	resize( 400,90 );
	setMinimumSize( 400, 90 );
	setMaximumSize( 400, 90 );
}


open_topData::~open_topData()
{
}
void open_topData::create_toplevel()
{
}
void open_topData::terminate()
{
}
