/**********************************************************************

	--- Qt Architect generated file ---

	File: open_ksircData.h
	Last generated: Wed Nov 26 22:18:02 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef open_ksircData_included
#define open_ksircData_included

#include <qdialog.h>
#include <qlined.h>

class open_ksircData : public QDialog
{
    Q_OBJECT

public:

    open_ksircData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~open_ksircData();

public slots:


protected slots:

    virtual void terminate();
    virtual void create_toplevel();

protected:
    QLineEdit* nameSLE;

};

#endif // open_ksircData_included
