/**********************************************************************

	--- Qt Architect generated file ---

	File: servercontrollerData.h
	Last generated: Sat Nov 29 23:47:14 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef servercontrollerData_included
#define servercontrollerData_included

#include "control.h"
#include "kmenubar.h"
#include "ktreelist.h"
#include <qframe.h>

class servercontrollerData : public KSircControl
{
    Q_OBJECT

public:

    servercontrollerData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~servercontrollerData();

public slots:


protected slots:


protected:
    QFrame* BaseBorder;
    KMenuBar* MenuBar;
    KTreeList* ConnectionTree;

};

#endif // servercontrollerData_included
