/**********************************************************************

	--- Qt Architect generated file ---

	File: KSCutDialogData.cpp
	Last generated: Tue Dec 30 00:04:04 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "KSCutDialogData.h"

#define Inherited QDialog

#include <qpushbt.h>
#include <qlayout.h>

KSCutDialogData::KSCutDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	IrcMLE = new QMultiLineEdit( this, "MultiLineEdit_2" );
	IrcMLE->setGeometry( 5, 5, 580, 315 );
	IrcMLE->setMinimumSize( 10, 10 );
	IrcMLE->setMaximumSize( 32767, 32767 );
	IrcMLE->insertLine( "" );
	IrcMLE->setReadOnly( FALSE );
	IrcMLE->setOverwriteMode( FALSE );

	QPushButton* dlgedit_PushButton_3;
	dlgedit_PushButton_3 = new QPushButton( this, "PushButton_3" );
	dlgedit_PushButton_3->setGeometry( 475, 5, 100, 30 );
	dlgedit_PushButton_3->setMinimumSize( 100, 30 );
	dlgedit_PushButton_3->setMaximumSize( 100, 30 );
	connect( dlgedit_PushButton_3, SIGNAL(clicked()), SLOT(terminate()) );
	dlgedit_PushButton_3->setText( "&Close" );
	dlgedit_PushButton_3->setAutoRepeat( FALSE );
	dlgedit_PushButton_3->setAutoResize( FALSE );
	dlgedit_PushButton_3->setAutoDefault( TRUE );

	QBoxLayout* dlgedit_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	dlgedit_layout_1->addStrut( 0 );
	dlgedit_layout_1->addWidget( IrcMLE, 1, 36 );
	QBoxLayout* dlgedit_layout_1_2 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	dlgedit_layout_1->addLayout( dlgedit_layout_1_2, 1 );
	dlgedit_layout_1_2->addStrut( 40 );
	dlgedit_layout_1_2->addWidget( dlgedit_PushButton_3, 1, 18 );


	resize( 590,370 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


KSCutDialogData::~KSCutDialogData()
{
}
void KSCutDialogData::terminate()
{
}
