/**********************************************************************

	--- Dlgedit generated file ---

	File: NewMsgDlgData.cpp
	Last generated: Fri Jul 18 14:49:43 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "NewMsgDlgData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

NewMsgDlgData::NewMsgDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE )
{
	typeList = new QListBox( this, "ListBox_1" );
	typeList->setGeometry( 10, 40, 260, 250 );
	connect( typeList, SIGNAL(selected(int)), SLOT(medit(int)) );
	typeList->setFrameStyle( 51 );
	typeList->setLineWidth( 2 );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "EditButton" );
	tmpQPushButton->setGeometry( 280, 40, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(medit()) );
	tmpQPushButton->setText( "Edit" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "CancelButton" );
	tmpQPushButton->setGeometry( 280, 260, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(cancel()) );
	tmpQPushButton->setText( "Cancel" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_1" );
	tmpQLabel->setGeometry( 10, 10, 260, 30 );
	tmpQLabel->setText( "Editable types" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	tmpQPushButton = new QPushButton( this, "PushButton_3" );
	tmpQPushButton->setGeometry( 280, 80, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(read()) );
	tmpQPushButton->setText( "Read file" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	resize( 390, 300 );
}


NewMsgDlgData::~NewMsgDlgData()
{
}
void NewMsgDlgData::medit(int)
{
}
void NewMsgDlgData::medit()
{
}
void NewMsgDlgData::cancel()
{
}
void NewMsgDlgData::read()
{
}
