/**********************************************************************

	--- Dlgedit generated file ---

	File: NewMsgDlgData.h
	Last generated: Fri Jul 18 14:49:43 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef NewMsgDlgData_included
#define NewMsgDlgData_included

#include <qdialog.h>
#include <qlistbox.h>

class NewMsgDlgData : public QDialog
{
    Q_OBJECT

public:

    NewMsgDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~NewMsgDlgData();

public slots:


protected slots:

    virtual void medit(int);
    virtual void medit();
    virtual void read();
    virtual void cancel();

protected:
    QListBox* typeList;

};

#endif // NewMsgDlgData_included
