/**********************************************************************

	--- Dlgedit generated file ---

	File: PartPropsData.cpp
	Last generated: Fri Jul 11 22:21:39 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "PartPropsData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

PartPropsData::PartPropsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE )
{
	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_2" );
	tmpQLabel->setGeometry( 10, 10, 100, 30 );
	tmpQLabel->setText( "Encoding" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	encodings = new QComboBox( FALSE, this, "ComboBox_1" );
	encodings->setGeometry( 110, 10, 100, 30 );
	encodings->setSizeLimit( 10 );
	encodings->setAutoResize( FALSE );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "CancelButton" );
	tmpQPushButton->setGeometry( 10, 80, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(cancel()) );
	tmpQPushButton->setText( "Cancel" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "OKButton" );
	tmpQPushButton->setGeometry( 120, 80, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(ok()) );
	tmpQPushButton->setText( "OK" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	resize( 230, 120 );
}


PartPropsData::~PartPropsData()
{
}
void PartPropsData::cancel()
{
}
void PartPropsData::ok()
{
}
