/**********************************************************************

	--- Dlgedit generated file ---

	File: PartPropsData.h
	Last generated: Fri Jul 11 22:21:38 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef PartPropsData_included
#define PartPropsData_included

#include <qdialog.h>
#include <qcombo.h>

class PartPropsData : public QDialog
{
    Q_OBJECT

public:

    PartPropsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~PartPropsData();

public slots:


protected slots:

    virtual void ok();
    virtual void cancel();

protected:
    QComboBox* encodings;

};

#endif // PartPropsData_included
