/**********************************************************************

	--- Dlgedit generated file ---

	File: PostDialogData.h
	Last generated: Fri Jul 18 20:30:46 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef PostDialogData_included
#define PostDialogData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qlined.h>
#include <qlistbox.h>
#include <qmlined.h>
#include <qpushbt.h>

class PostDialogData : public QDialog
{
    Q_OBJECT

public:

    PostDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~PostDialogData();

public slots:


protected slots:

    virtual void editPart(int);
    virtual void propsPart();
    virtual void addPart();
    virtual void postLater();
    virtual void showHelp();
    virtual void removePart();
    virtual void editPart();
    virtual void select(int);
    virtual void cancel();
    virtual void postNow();

protected:
    QMultiLineEdit* errorList;
    QPushButton* postNBtn;
    QPushButton* editBtn;
    QPushButton* cancelBtn;
    QListBox* partList;
    QPushButton* addBtn;
    QPushButton* removeBtn;
    QPushButton* propsBtn;
    QLabel* helpLabel;
    QPushButton* postLBtn;
    QLineEdit* subject;
    QLineEdit* newsgroup;

};

#endif // PostDialogData_included
