/**********************************************************************

	--- Qt Architect generated file ---

	File: defaultfiltersdata.cpp
	Last generated: Tue Feb 17 09:36:02 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "defaultfiltersdata.h"

#define Inherited QFrame

#include <qlabel.h>
#include <qbttngrp.h>

defaultfiltersdata::defaultfiltersdata
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* dlgedit_ButtonGroup_4;
	dlgedit_ButtonGroup_4 = new QButtonGroup( this, "ButtonGroup_4" );
	dlgedit_ButtonGroup_4->setGeometry( 80, 235, 225, 55 );
	dlgedit_ButtonGroup_4->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_4->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_4->setFrameStyle( 49 );
	dlgedit_ButtonGroup_4->setTitle( "Higlight Your Nick" );
	dlgedit_ButtonGroup_4->setAlignment( 1 );

	QButtonGroup* dlgedit_ButtonGroup_2;
	dlgedit_ButtonGroup_2 = new QButtonGroup( this, "ButtonGroup_2" );
	dlgedit_ButtonGroup_2->setGeometry( 80, 110, 225, 120 );
	dlgedit_ButtonGroup_2->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_2->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_2->setFrameStyle( 49 );
	dlgedit_ButtonGroup_2->setTitle( "Colour Nicks in Channels" );
	dlgedit_ButtonGroup_2->setAlignment( 1 );

	QButtonGroup* dlgedit_ButtonGroup_1;
	dlgedit_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	dlgedit_ButtonGroup_1->setGeometry( 80, 5, 225, 100 );
	dlgedit_ButtonGroup_1->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_1->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_1->setFrameStyle( 49 );
	dlgedit_ButtonGroup_1->setTitle( "Allow External Colours" );
	dlgedit_ButtonGroup_1->setAlignment( 1 );

	kSircColours = new QCheckBox( this, "CheckBox_1" );
	kSircColours->setGeometry( 110, 20, 170, 30 );
	kSircColours->setMinimumSize( 10, 10 );
	kSircColours->setMaximumSize( 32767, 32767 );
	kSircColours->setText( "Allow &kSirc Colour codes" );
	kSircColours->setAutoRepeat( FALSE );
	kSircColours->setAutoResize( FALSE );
	kSircColours->setChecked( TRUE );

	mircColours = new QCheckBox( this, "CheckBox_2" );
	mircColours->setGeometry( 110, 55, 170, 30 );
	mircColours->setMinimumSize( 10, 10 );
	mircColours->setMaximumSize( 32767, 32767 );
	mircColours->setText( "&Allow &mirc Colour codes" );
	mircColours->setAutoRepeat( FALSE );
	mircColours->setAutoResize( FALSE );
	mircColours->setChecked( TRUE );

	NickFColour = new KNumericSpinBox( this, "User_1" );
	NickFColour->setGeometry( 195, 145, 55, 30 );
	NickFColour->setMinimumSize( 10, 10 );
	NickFColour->setMaximumSize( 32767, 32767 );

	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 95, 125, 120, 20 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	dlgedit_Label_1->setText( "-1 means no colour" );
	dlgedit_Label_1->setAlignment( 289 );
	dlgedit_Label_1->setMargin( -1 );

	NickBColour = new KNumericSpinBox( this, "User_2" );
	NickBColour->setGeometry( 195, 185, 55, 30 );
	NickBColour->setMinimumSize( 10, 10 );
	NickBColour->setMaximumSize( 32767, 32767 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 90, 140, 100, 30 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "Foreground" );
	dlgedit_Label_2->setAlignment( 290 );
	dlgedit_Label_2->setMargin( -1 );

	LabelNickB = new QLabel( this, "Label_3" );
	LabelNickB->setGeometry( 90, 185, 100, 30 );
	LabelNickB->setMinimumSize( 10, 10 );
	LabelNickB->setMaximumSize( 32767, 32767 );
	LabelNickB->setText( "Background" );
	LabelNickB->setAlignment( 290 );
	LabelNickB->setMargin( -1 );

	QLabel* dlgedit_Label_4;
	dlgedit_Label_4 = new QLabel( this, "Label_4" );
	dlgedit_Label_4->setGeometry( 90, 140, 100, 30 );
	dlgedit_Label_4->setMinimumSize( 10, 10 );
	dlgedit_Label_4->setMaximumSize( 32767, 32767 );
	dlgedit_Label_4->setText( "Foreground" );
	dlgedit_Label_4->setAlignment( 290 );
	dlgedit_Label_4->setMargin( -1 );

	QLabel* dlgedit_Label_5;
	dlgedit_Label_5 = new QLabel( this, "Label_5" );
	dlgedit_Label_5->setGeometry( 90, 145, 100, 30 );
	dlgedit_Label_5->setMinimumSize( 10, 10 );
	dlgedit_Label_5->setMaximumSize( 32767, 32767 );
	dlgedit_Label_5->setText( "Foreground" );
	dlgedit_Label_5->setAlignment( 290 );
	dlgedit_Label_5->setMargin( -1 );

	QLabel* dlgedit_Label_6;
	dlgedit_Label_6 = new QLabel( this, "Label_6" );
	dlgedit_Label_6->setGeometry( 90, 250, 100, 30 );
	dlgedit_Label_6->setMinimumSize( 10, 10 );
	dlgedit_Label_6->setMaximumSize( 32767, 32767 );
	dlgedit_Label_6->setText( "Colour" );
	dlgedit_Label_6->setAlignment( 290 );
	dlgedit_Label_6->setMargin( -1 );

	usHighlightColour = new KNumericSpinBox( this, "User_5" );
	usHighlightColour->setGeometry( 195, 250, 55, 30 );
	usHighlightColour->setMinimumSize( 10, 10 );
	usHighlightColour->setMaximumSize( 32767, 32767 );



	dlgedit_ButtonGroup_1->insert( kSircColours );
	dlgedit_ButtonGroup_1->insert( mircColours );

	resize( 400,300 );
	setMinimumSize( 400, 300 );
	setMaximumSize( 400, 300 );
}


defaultfiltersdata::~defaultfiltersdata()
{
}
